services:

  db:
    ports:
      - "3306:3306"

  backend:
    ports:
      - "8000:8000"
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - dev
      - --host
      - 0.0.0.0
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./backend/htmlcov:/app/backend/htmlcov
    environment:
      FASTAPI_ENV: "development"
      SMTP_HOST: "mailpit"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
